apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: country-service
  template:
    metadata:
      labels:
        app: country-service
    spec:
      containers:
        - name: myapp-container
          image: nginx:latest  # ON UTILISE NGINX POUR LE TEST
          ports:
            - containerPort: 80 # Nginx écoute sur le port 80
