apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: country-service
  template:
    metadata:
      labels:
        app: country-service
    spec:
      containers:
        - name: myapp-container
          # On utilise l'image du cours qui contient le Swagger
          image: jmouna/my-country-service:22 
          ports:
            - containerPort: 8082
