apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: country-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: country-service
  template:
    metadata:
      labels:
        app: country-service
    spec:
      containers:
        - name: myapp-container
          # Utilisez l'image que vous avez envoyée sur Docker Hub
          image: omaymaajabri/my-country-service:12
          ports:
            - containerPort: 8082
